# -*- coding: utf-8 -*-
"""Cirq

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vrb2B2YPeZgitghveqt3do8G_r1YYaid
"""

import cirq

# Pick a qubit.
qubit = cirq.GridQubit(0, 0)

# Create a circuit
circuit = cirq.Circuit(
    cirq.X(qubit)**0.5,  # Square root of NOT.
    cirq.measure(qubit, key='m')  # Measurement.
)
print("Circuit:")
print(circuit)

# Simulate the circuit several times.
simulator = cirq.Simulator()
result = simulator.run(circuit, repetitions=20)
print("Results:")
print(result)

!pip install cirq